# Generated by Django 4.2.3 on 2024-02-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='donor/images/')),
                ('blood_group', models.CharField(choices=[('a+', 'a+'), ('a-', 'a-'), ('b+', 'b+'), ('b-', 'b-'), ('ab+', 'ab+'), ('ab-', 'ab-'), ('o+', 'o+'), ('o-', 'o-')], max_length=10)),
                ('last_donate_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('disease', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donormodel')),
            ],
        ),
    ]
