# Generated by Django 4.2.3 on 2024-02-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donormodel',
            name='image',
            field=models.ImageField(upload_to='donor/media/images/'),
        ),
    ]
