# Generated by Django 4.2.3 on 2024-02-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=30)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('blood_group', models.CharField(choices=[('a+', 'a+'), ('a-', 'a-'), ('b+', 'b+'), ('b-', 'b-'), ('ab+', 'ab+'), ('ab-', 'ab-'), ('o+', 'o+'), ('o-', 'o-')], max_length=50)),
                ('image', models.ImageField(default='images/female_avater.png', upload_to='images/user/')),
                ('last_donate', models.DateField()),
                ('availabilities', models.BooleanField(default=True)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.division')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.division'),
        ),
    ]
