# Generated by Django 4.2.3 on 2024-03-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_blood_group_alter_usermodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='images/male_avatar.jpg', upload_to='images/user/'),
        ),
    ]
